
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../component/NavBar.jsx";
import NextThemeProvider from "../provider/NextThemeProvider.jsx";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body >
        <NextThemeProvider>
        <NavBar />
        <div className="flex-1 overflow-y-auto">
          {children}
        </div>
        </NextThemeProvider>
        </body>
    </html>
  );
}
