
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import NavBar from "../component/NavBar.jsx";
// import NextThemeProvider from "../provider/NextThemeProvider.jsx";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en" suppressHydrationWarning
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body >
//         <NextThemeProvider>
//         <NavBar />
//         <div className="flex-1 overflow-y-auto">
//           {children}
//         </div>
//         </NextThemeProvider>
//         </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Poppins, DM_Mono } from "next/font/google";

import "./globals.css";
import NavBar from "../component/NavBar.jsx";
import NextThemeProvider from "../provider/NextThemeProvider.jsx";

// Existing fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// NEW MODERN FONTS
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  weight: ["300", "400", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "StudyNook-Home",
  description: "A Library Room Booking System for Students",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} ${dmMono.variable} h-full antialiased`}
    >
      <body className="bg-olive-100">
        <NextThemeProvider>
          <NavBar />
          <div className="flex-1 overflow-y-auto">{children}</div>
        </NextThemeProvider>
      </body>
    </html>
  );
}